/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mango-v1.glb --tranform 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
	const { nodes, materials } = useGLTF("/models/mango-v1.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.mango.geometry}
				material={materials.skin}
				rotation={[-1.821, 0.017, -0.072]}
			/>
		</group>
	);
}

useGLTF.preload("/mango-v1.glb");
