/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 papaya-v1.glb --transform 
Files: papaya-v1.glb [3.1MB] > /Users/biancasilva/workspace/threejs/flying-fruit/public/models/papaya-v1-transformed.glb [223.08KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/papaya-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.papaya.geometry} material={materials.skin} rotation={[-0.47, -0.369, 1.39]} />
    </group>
  )
}

useGLTF.preload('/papaya-v1-transformed.glb')
