/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pitaya-v1.glb --transform 
Files: pitaya-v1.glb [13.42MB] > /Users/biancasilva/workspace/threejs/flying-fruit/public/models/pitaya-v1-transformed.glb [1.33MB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pitaya-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pitaya.geometry} material={materials.skin} rotation={[3.114, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/pitaya-v1-transformed.glb')
